name: Deploy Storybook to GitHub Pages

on:
  push:
	  branches:
			- main
		paths:
			- 'packages/magnolui/**'
	workflow_dispatch:

permissions:
	contents: read
	pages: write
	id-token: write

concurrency:
	group: 'pages'
	cancel-in-progress: true

jobs:
	build:
		name: Build Storybook
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Setup PNPM
				uses: pnpm/action-setup@v4
				with:
					version: 10.12.1

			- name: Setup Node
				uses: actions/setup-node@v4
				with:
					node-version: 20
					cache: pnpm

			- name: Install dependencies
				run: pnpm install --frozen-lockfile

			- name: Build Storybook
				run: pnpm build:storybook

			- name: Upload artifact
				uses: actions/upload-pages-artifact@v3
				with:
					path: packages/docs/storybook-static

	deploy:
		name: Deploy to GitHub Pages
		needs: build
		runs-on: ubuntu-latest
		environment:
			name: github-pages
			url: ${{ steps.deployment.outputs.page_url }}
		steps:
			- name: Deploy
				id: deployment
				uses: actions/deploy-pages@v4

